---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candycrush-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candycrush
  template:
    metadata:
      labels:
        app: candycrush
    spec:
      containers:
      - name: candycrush
        image: dinesh1097/candycrushgithubaction:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: candycrush-service
spec:
  selector:
    app: candycrush
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
